#!/usr/bin/bash

# This script is used to build the java project.

rm -r bin spaceplus/jsp;

mkdir spaceplus/jsp;

# Print command and stops on error
set -ex

# Find all the java files in the src folder.
find . -name "*.java" > sources;

# Compile the java project.
javac -Xlint:unchecked -d bin -cp "lib/*" @sources;

# Remove the sources file.
rm sources;

# Extra
cp spaceplus/http/LocalStrings.properties bin/spaceplus/http/LocalStrings.properties;
